version: '3.8'

x-common-config:
  # 提取相同的配置部分
  &common-config
  restart: unless-stopped
  networks:
    - ecommerce

services:

  backend:
    container_name: ecommerce_django
    image: zoe-ecommerce/python:1.0.0
    ports:
      - "8100:8000"
    volumes:
      #- /etc/nginx/html/ecommerce/staticfiles/admin:/opt/web/staticfiles/admin
      - /etc/nginx/html/ecommerce/static:/opt/web/static
      - /opt/web/ecommerce/db.sqlite3:/opt/web/db.sqlite3
      - /opt/web/ecommerce/media:/opt/web/media
    env_file:
      - .env
    <<: *common-config

networks:
  ecommerce:
    name: ecommerce
    driver: bridge
