version: '3.8'

x-common-config:
  # 提取相同的配置部分
  &common-config
  restart: unless-stopped
  networks:
    - blog

services:

  backend:
    container_name: django
    image: zoe-blog/python:1.0.1
    ports:
      - "8000:8000"
    volumes:
      - /etc/nginx/html/staticfiles:/opt/web/staticfiles
      - /opt/web/blog/media:/opt/web/media
    <<: *common-config

networks:
  blog:
    name: blog
    driver: bridge
