version: '3.8'

x-common-config:
  # 提取相同的配置部分
  &common-config
  restart: unless-stopped
  networks:
    - blog

services:

  backend:
    container_name: django
    image: zoe-blog/python:1.0.0
    ports:
      - "8000:8000"
    <<: *common-config

networks:
  blog:
    name: blog
    driver: bridge
