# Generated by Django 4.2.15 on 2024-11-27 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, choices=[('TW', '台灣'), ('CN', '中國'), ('US', '美國'), ('JP', '日本'), ('KR', '韓國'), ('SG', '新加坡'), ('MY', '馬來西亞'), ('TH', '泰國'), ('VN', '越南'), ('ID', '印尼'), ('PH', '菲律賓'), ('AU', '澳洲'), ('NZ', '紐西蘭'), ('CA', '加拿大'), ('GB', '英國'), ('FR', '法國'), ('DE', '德國'), ('IT', '義大利'), ('ES', '西班牙'), ('PT', '葡萄牙'), ('NL', '荷蘭'), ('BE', '比利時'), ('SE', '瑞典'), ('NO', '挪威'), ('FI', '芬蘭'), ('DK', '丹麥')], max_length=2)),
                ('role', models.CharField(choices=[('boss', '老闆'), ('consumer', '客人')], default='consumer', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
