version: '3.8'

x-common-config:
  # 提取相同的配置部分
  &common-config
  restart: unless-stopped
  networks:
    - ecommerce

services:

  backend:
    container_name: django
    image: zoe-ecommerce/python:1.0.0
    ports:
      - "8000:8000"
    volumes:
      - /etc/nginx/html/staticfiles:/opt/web/staticfiles
      - backend_media:/opt/web/media
    <<: *common-config

networks:
  ecommerce:
    name: ecommerce
    driver: bridge

volumes:
  backend_media:
    name: backend_media
